export const SET_ASSIGNMENTS = 'SET_ASSIGNMENTS';
export const SET_NOTICES = 'SET_NOTICES';
export const SET_FEEDBACK = 'SET_FEEDBACK';
export const SET_RECEIVED_FEEDBACK_BY_TEACHER = 'SET_RECEIVED_FEEDBACK_BY_TEACHER';
export const SET_SENT_FEEDBACK_BY_STUDENT = 'SET_SENT_FEEDBACK_BY_STUDENT'