export const STARTED = 'STARTED'

export const SET_ASSIGNMENTS = 'SET_ASSIGNMENTS';
export const SET_NOTICES = 'SET_NOTICES';
export const SET_FEEDBACK = 'SET_FEEDBACK';
export const SET_USERS = 'SET_USERS';

export const ADD_TEACHER_ASSIGNMENT = "ADD_TEACHER_ASSIGNMENT";
export const SET_UPDATED_NOTICES = 'SET_UPDATED_NOTICES';


export const AUTH_STUDENT = 'AUTH_STUDENT';
export const AUTH_TEACHER = 'AUTH_TEACHER';

export const ADD_TEACHER = 'ADD_TEACHER';
export const ADD_STUDENT = 'ADD_STUDENT';

export const ADD_STUDENT_TO_ASSIGNMENT = 'ADD_STUDENT_TO_ASSIGNMENT';
export const ADD_TEACHER_TO_ASSIGNMENT = 'ADD_TEACHER_TO_ASSIGNMENT';

export const CHANGE_AUTH_USER = 'CHANGE_AUTH_USER';

export const ADD_NOTICE = 'ADD_NOTICE'